pipeline{
  agent any 
  tools{
    jdk 'jdk17'
    nodejs 'node18'
  }
  environment{
    SONAR_HOME=tool 'sonar-scanner'
  }
  stages{
    stage("Clean Workspace"){
      steps{
        cleanWs()
      }
    }
    stage("Git Checkout"){
      steps{
        dir('backend'){
          git branch:'main', url:'https://github.com/Yatingambhir85/wanderlust---Yatin'
      }
      } 
    }
    stage("Static code analysis"){
      steps{
        withSonarQubeEnv('sonar-server'){
          sh '$SONAR_HOME/bin/sonar-scanner -Dsonar.projectName=wanderlust-backend -Dsonar.projectKey=wanderlust-backend'
        }
      }
    }
  }
}
