pipeline{
  agent any 
  tools{
    jdk 'jdk17'
    nodejs 'node18'
  }
  environment{
    SONAR_HOME = tool 'sonar-scanner'
  }
  stages{
    stage("Clean Workspace"){
      steps{
        cleanWs()
      }
    }
    stage("Git Checkout"){
      steps{
          checkout scmGit(branches: [[name: '*/main']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'backend']], userRemoteConfigs: [[url: 'https://github.com/Yatingambhir85/wanderlust/']])
      } 
    }
    stage("SONAR-SCANNING"){
      steps{
        withSonarQubeEnv('sonar-server'){
          sh '$SONAR_HOME/bin/sonar-scanner -Dsonar.projectName=wanderlust-backend -Dsonar.projectKey=wanderlust-backend'
        }
      }
    }
  }
}
